### ISSUE TITLE
making it installable as a global package

### ISSUE THREAD

**Issue by Haroenv** [KittyGiraudel/map-dater#1]
this should be adding this in your `package.json`:

``` json
"bin": {
  "map-dater": "./src/index.js"
},
```

After that you can either put it on `npm` by doing `npm login; npm publish` or asking people to do `npm install -g HugoGiraudel/map-dater`.

**Comment by KittyGiraudel** [comment]
I don’t think this makes sense to have it on npm. It’s a fun project, and unless someone explicitly wants to use it as a dependency, I believe it’s fine to leave it as is it.

**Comment by Haroenv** [comment]
Makes sense, but it's still useful (in my opinion) to put the `bin` value so you can install with npm from GitHub. It doesn't have to be published for that.

**Comment by KittyGiraudel** [comment]
Definitely.

**Comment by KittyGiraudel** [comment]
Done. :)
